import * as THREE from "three";

export function createAppState() {
  return {
    scene: null,
    camera: null,
    renderer: null,
    xrSession: null,
    xrReferenceSpace: null,
    xrViewerSpace: null,
    xrHitTestSource: null,
    xrPlacementAnchor: null,
    xrPlacementAnchorSpace: null,
    latestHit: null,
    latestHitResult: null,
    reticle: null,
    planeIndicator: null,
    sunLight: null,
    shadowReceiver: null,
    modelAssets: null,
    bouldersRoot: null,
    floatingObject: null,
    floatingObjectBaseWorldPosition: new THREE.Vector3(),
    floatingObjectTargetWorldPosition: new THREE.Vector3(),
    floatingObjectPlacedAtTime: 0,
    floatingObjectTriggered: false,
    floatingObjectRiseProgress: 0,
    foundationFadeStarted: false,
    foundationFadeMeshes: [],
    floatingObjectRevealMeshes: [],
    floatingObjectRevealStarted: false,
    dustObject: null,
    dustRevealQueued: false,
    dustRevealMeshes: [],
    dustRevealComplete: false,
    stageRockObjects: { 1: null, 2: null, 3: null },
    stageRockMeshes: { 1: [], 2: [], 3: [] },
    visibleFormationStage: 5,
    stageTransitionActive: false,
    fadeTasks: [],
    formationStep: 4,
    childRevealRequested: false,
    placementButtonReady: false,
    arSupportChecked: false,
    arSupported: false,
    assetProgress: 0,
    modelsLoaded: false,
    modelLoadError: false,
    placementCenter: new THREE.Vector3(),
    planeHeight: 0,
    bouldersPlaced: false,
    animationStarted: false,
    animationComplete: false,
    lastTime: 0,
    hitFrames: 0,
    noHitFrames: 0,
    lastScanDebugTime: 0,
    compassHeadingDegrees: null,
    userPosition: null,
    userPositionError: null,
    geolocationWatchId: null,
    sunDirection: new THREE.Vector3(-0.3, 0.8, 0.5).normalize(),
    lastSunPosition: null,
    sunReady: false,
    domOverlayActive: false,
    xrHud: null
  };
}
