import * as THREE from "three";

export function createAppState() {
  return {
    scene: null,
    camera: null,
    renderer: null,
    xrSession: null,
    xrReferenceSpace: null,
    xrViewerSpace: null,
    xrHitTestSource: null,
    xrPlacementAnchor: null,
    xrPlacementAnchorSpace: null,
    latestHit: null,
    latestHitResult: null,
    placementReticle: null,
    sunLight: null,
    shadowReceiver: null,
    modelAssets: null,
    formationRoot: null,
    arSupportChecked: false,
    arSupported: false,
    assetProgress: 0,
    modelsLoaded: false,
    modelLoadError: false,
    placementCenter: new THREE.Vector3(),
    planeHeight: 0,
    formationPlaced: false,
    lastTime: 0,
    hitFrames: 0,
    noHitFrames: 0,
    lastScanDebugTime: 0,
    userPosition: null,
    userPositionError: null,
    geolocationWatchId: null,
    sunDirection: new THREE.Vector3(-0.3, 0.8, 0.5).normalize(),
    lastSunPosition: null,
    sunReady: false
  };
}
